### ISSUE TITLE
Author is a genious

### ISSUE THREAD

**Issue by clementiae** [sanstorik/server_face_recognition#1]
https://github.com/sanstorik/server_face_recognition/blob/6a9c4a05d1ecd68218e56a3f757979f108b4484c/src/main/java/org/sanstorik/http_server/Token.java#L12
I'd suggest using secret application keys as environmental variables
)

**Comment by sanstorik** [comment]
Hi. Thank you for your response!

Dear phlshlpme, mojete idti nahui! Spasibo!

**Comment by sanstorik** [comment]
Fixed. Thank you for contributing into my project.
