### ISSUE TITLE
How to start the server

### ISSUE THREAD

**Issue by paradoxalan** [sanstorik/server_face_recognition#2]
How do you run this app server?

**Comment by sanstorik** [comment]
First of all you have to setup java&maven.
Run the server on some port, for example like this (I was running it on Glassfish 4)

![image](https://user-images.githubusercontent.com/24196067/93344917-87e1d900-f832-11ea-87dc-e5ff3c8c9e9a.png)
After that create postgressql database with table User (id, username, password, image_url, json_url), there is an sql for that.

**Comment by paradoxalan** [comment]
Thanks
